---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: auto-deployment
  namespace: flux-system
spec:
  image: nikowoj900/multi-stage-build
  interval: 1m0s
  secretRef:
    name: regcred

