apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-stage-build
  namespace: auto-deployment
spec:
  selector:
    matchLabels:
      app: multi-stage-build
  template:
    metadata:
      labels:
        app: multi-stage-build
    spec:
      containers:
        - name: multi-stage-build
          image: nikowoj900/multi-stage-build:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP