---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: auto-deployment
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: auto-deployment
  policy:
    semver:
      range: 1.0.x

