---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  force: false
  interval: 5m0s
  path: ./flux/clusters/my-cluster/secrets
  prune: true
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system